apiVersion: v1
kind: Service
metadata:
  name: flaskee-service
spec:
  selector:
    app: flaskee
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: app
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskee
spec:
  selector:
    matchLabels:
      app: flaskee
  replicas: 3
  template:
    metadata:
      labels:
        app: flaskee
    spec:
      containers:
      - name: flaskee
        image: flaskee:latest
        imagePullPolicy: Never
        ports:
        - name: app 
          port: 3000
