apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flaskee.fullname" . }}
  labels:
    {{- include "flaskee.labels" . | nindent 4 }}
spec:
  replicas: 3
  selector:
    matchLabels:
      {{- include "flaskee.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flaskee.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: app
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: app
          readinessProbe:
            httpGet:
              path: /healthz
              port: app

