apiVersion: v1
kind: Service
metadata:
  name: {{ include "flaskee.fullname" . }}
  labels:
    {{- include "flaskee.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: app
      protocol: TCP
  selector:
    {{- include "flaskee.selectorLabels" . | nindent 4 }}
